name: CrystalKillListener
main: cn.guangchen233.crystallistener.plugin.CrystalListener
version: 1.3-SNAPSHOT
author: GuangChen233
website: https://github.com/GuangChen2333/CrystalKillListener
api-version: 1.12