name: CrystalKillListener
main: cn.guangchen233.crystallistener.plugin.Main
version: 2.0.0-SNAPSHOT
author: GuangChen233
website: https://github.com/GuangChen2333/CrystalKillListener
api-version: 1.12